/*
 * This source file was generated by the Gradle 'init' task
 */
package learn.java.records;

public class App {
    public static void main(String[] args) {
        // Traditional approach
        NormalClass normalClass = new NormalClass(10, 20);
        System.out.println("Hello x: " + normalClass.getX() + " and y: " + normalClass.getY());

        // Java Records approach
        RecordClass recordClass = new RecordClass(100, 200);
        System.out.println("Hello Record x: " + recordClass.x() + " and y: " + recordClass.y());
    }
}
