server:
  port: 8090
  servlet:
    context-path: /v1

spring:
  application:
    title: Learn Spring Boot
    version: v3.0.4
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/jfswd_1_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
