spring:
  application:
    name: spring-security

#  security:
#    user:
#      name: username
#      password: password
#      roles: admin,supplier

logging:
  level:
    org:
      springframework:
        security: TRACE
